### ISSUE TITLE
Question about the getDocumentThumbnail function

### ISSUE THREAD

**Issue by shaosh** [gian788/node-box-view#1]
Hi gian788,

Thanks for developing this client. I am trying to use it to get thumbnail of a document. I am sure the document id is valid, and the code does create the file thumb.bmp and it does have some data. However when I trying to open the file, it returns the image has bad format. Do you have any idea about the reason? 

Here is my code:
        var myKey = <mykey>;
        var boxViewLib = require('../../node_modules/node-box-view');
        var boxView = new boxViewLib(myKey); 
        boxView.getDocumentThumbnail('85f1375815f3480cb55499fcae7df336', 800, 500, '/documents/designashirt/artexpress/src/client/thumb.bmp', function(err,res){
            console.log(err, res);
          });

Thank you,
shaosh

**Comment by gian788** [comment]
Hi Shaosh,
probably you are reciving an 202 response from api, that mean the thumbnail isn't ready yet.
Now the client handles this kind of response and returns an error.
